server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  #文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # 邮箱配置
  mail:
    # 平台地址
    host: smtp.qq.com
    # 端口号
    port: 587
    # 发送邮箱地址，邮箱号
    username: zhuyuqinss@qq.com
    # 授权码
    password: wwmreuijtqrldgeb
    properties:
      mail:
          ssl:
            # ssl加密
            enable: true
    default-encoding: utf-8
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

# 文件上传本地路径
basePath: E:\javaWeb\workspace\image\