server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  #文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID

# 文件上传本地路径
basePath: /usr/local/image/